services:
  goapp:
    container_name: goapp
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:8080
    env_file: .env
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file: .env


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file: .env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_INITDB_ROOT_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_INITDB_ROOT_PASSWORD 
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_INITDB_ROOT_USERNAME:$MONGO_INITDB_ROOT_PASSWORD@mongo:27017/
    depends_on:
      - mongo


volumes:
  api:
  mongo: